language: R
r: release
cache: packages
sudo: required
pandoc_version: 1.19.2.1

git:
  depth: 1

branches:
  only: master

r_binary_packages:
  - ape
  - knitr
  - phangorn
  - R.cache
  - stringi

r_packages:
  - bookdown
  - rcrossref

r_github_packages:
  - ms609/TreeSearch
  - ms609/Morphobank
  - TGuillerme/Inapp

before_install:
  - sudo add-apt-repository -y ppa:cran/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - travis_wait 43 ./_build.sh
  - ./_deploy.sh

addons:
  apt:
    packages:
      - ghostscript
