language: R
r: release
cache: packages
sudo: required
latex: false

git:
  depth: 1

branches:
  only: master

r_binary_packages:
  - ape
  - knitr
  - phangorn
  - R.cache
  - rcrossref
  - stringi

r_packages:
  - bookdown

r_github_packages:
  - ms609/TreeSearch
  - ms609/Morphobank
  - TGuillerme/Inapp

script: travis_wait 43 Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  local_dir: _book
  on:
    branch: master
