Italicize <- function (string) {
  string <- gsub(paste0("\\b(",
                        paste0(gsub("_", "|", fixed = TRUE,
                                    c(taxa_names,

                                      'Acila', 'Antalis', 'Apotocardium',
                                      'Bactrotheca', 'Bethia', 'Bowerbankia',
                                      'Calloria', 'Crania',
                                      'Diadeloplax', 'Disoma', 'Discinisca',
                                      'Eichwaldia', 'Electra', 'Enchytraeus',
                                      'Epimenia',
                                      'Equisetum', 'Eoorthis',
                                      'Fredericella',
                                      'Galeolaria', 'Glottidia', 'Gompholites',
                                      'Gryphus',
                                      'Hadrotreta', 'Harmothoe', 'Hydroides',
                                      'Hyolithes',
                                      'Ischnochiton', 'Kraussina',
                                      'Laevipilina', 'Lingulella', 'Lingulotreta',
                                      'Lochkothele', 'Loxosoma', 'Loxosomatoides',
                                      'Magelona', 'Membranipora', 'Mopalia',
                                      'Nereis', 'Neocrania', 'Neoancistrocrania',
                                      'Notosaria', 'Nucula',
                                      'Oikozetetes',
                                      'Paracraniops', 'Paramicrocornus',
                                      'Phascolion',
                                      'Phylactolaemata',
                                      'Phoronopsis', 'Phragmochaeta',
                                      'Protobalanus',
                                      'Recilites',
                                      'Sabella', 'Scolelepis',
                                      'Terebratalia', 'Themiste', 'Tubulipora',
                                      'Vema',
                                      'Yoldia',

                                      'atkinsae', 'comleyensis', 'cyrene', 'decaius',
                                      'deleta', 'minuta', 'murmanica',
                                      'schucherti', 'tenuis', 'worsleyi',

                                      'vascula', 'genitalia','lateralia',
                                      'media', 'myaria', 'terminalia',
                                      'levator ani',
                                      'et al\\.', 'et al', 'sensu')),
                               collapse='|'),
                        ")\\b"), "_\\1_", string, perl=TRUE, ignore.case=FALSE)
  gsub("\\b([A-Z]\\.) _([a-z])", "_\\1 \\2", string, perl=TRUE)
}
